version: "3.9"
services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://<username>:<password>@flask_db:<port>/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
#    if you wish to change the port, change both numbers here
    ports:
      - "5432:5432"
#    and set this port to the same. If using port 5432, this command is not needed
#    command: -p 5434
    environment:
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=<username>
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}